# Generated by Django 5.0.2 on 2024-02-11 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominal_value', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('ip_adress', models.GenericIPAddressField(default='251.242.129.25')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('bank', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_value', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.loans')),
            ],
        ),
    ]
