# Generated by Django 5.0.2 on 2024-02-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='ip_adress',
            field=models.GenericIPAddressField(default='163.79.138.206'),
        ),
    ]
